In [3]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 3.0.6
NumPy: 2.5.4

In [ ]:
df = pd.read_csv("../data/raw/2019-Oct.csv", nrows=10)
df

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,cart,5773203,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
1,2019-10-01 00:00:03 UTC,cart,5773353,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
2,2019-10-01 00:00:07 UTC,cart,5881589,2151191071051219817,NaN,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
3,2019-10-01 00:00:07 UTC,cart,5723490,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
4,2019-10-01 00:00:15 UTC,cart,5881449,1487580013522845895,NaN,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
5,2019-10-01 00:00:16 UTC,cart,5857269,1487580005134238553,NaN,runail,2.62,430174032,73dea1e7-664e-43f4-8b30-d32b9d5af04f
6,2019-10-01 00:00:19 UTC,cart,5739055,1487580008246412266,NaN,kapous,4.75,377667011,81326ac6-daa4-4f0a-b488-fd0956a78733
7,2019-10-01 00:00:24 UTC,cart,5825598,1487580009445982239,NaN,NaN,0.56,467916806,2f5b5546-b8cb-9ee7-7ecd-84276f8ef486
8,2019-10-01 00:00:25 UTC,cart,5698989,1487580006317032337,NaN,NaN,1.27,385985999,d30965e8-1101-44ab-b45d-cc1bb9fae694
9,2019-10-01 00:00:26 UTC,view,5875317,2029082628195353599,NaN,NaN,1.59,474232307,445f2b74-5e4c-427e-b7fa-6e0a28b156fe

In [6]:
df.columns

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     10 non-null     str
 1   event_type     10 non-null     str
 2   product_id     10 non-null     int64
 3   category_id    10 non-null     int64
 4   category_code  0 non-null      float64
 5   brand          7 non-null      str
 6   price          10 non-null     float64
 7   user_id        10 non-null     int64
 8   user_session   10 non-null     str
dtypes: float64(2), int64(3), str(4)
memory usage: 852.0 bytes

In [8]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,cart,5773203,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
1,2019-10-01 00:00:03 UTC,cart,5773353,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
2,2019-10-01 00:00:07 UTC,cart,5881589,2151191071051219817,NaN,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
3,2019-10-01 00:00:07 UTC,cart,5723490,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
4,2019-10-01 00:00:15 UTC,cart,5881449,1487580013522845895,NaN,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9

In [9]:
df["event_time"] = pd.to_datetime(df["event_time"], utc=True)
df["event_time"].dtype

datetime64[us, UTC]

In [13]:
path = "../data/raw/2019-Oct.csv"

total_rows = 0
missing_count = 0

for chunk in pd.read_csv(path, usecols=["category_code"], chunksize=100_000):
    total_rows += len(chunk)
    missing_count += chunk["category_code"].isna().sum()

missing_rate = missing_count / total_rows * 100

print(f"Всего строк: {total_rows}")
print(f"Пропусков: {missing_count}")
print(f"Доля пропусков: {missing_rate:.2f}%")

Всего строк: 4102283
Пропусков: 4034806
Доля пропусков: 98.36%

In [15]:
path = "../data/raw/2019-Oct.csv"

total_rows = 0
missing_count = 0

for chunk in pd.read_csv(path, usecols=["user_session"], chunksize=100_000):
    total_rows += len(chunk)
    missing_count += chunk["user_session"].isna().sum()

missing_rate = missing_count / total_rows * 100

print(f"Всего строк: {total_rows}")
print(f"Пропусков: {missing_count}")
print(f"Доля пропусков: {missing_rate:.2f}%")

Всего строк: 4102283
Пропусков: 637
Доля пропусков: 0.02%

In [17]:
event_counts = pd.Series(dtype="int64")

for chunk in pd.read_csv(path, usecols=["event_type"], chunksize=100_000):
    counts = chunk["event_type"].value_counts()
    event_counts = event_counts.add(counts, fill_value=0)

event_counts = event_counts.astype("int64")
print(event_counts.sort_values(ascending=False))

event_type
view                1862164
cart                1232385
remove_from_cart     762110
purchase             245624
dtype: int64

In [19]:
path = "../data/raw/2019-Oct.csv"

total_rows = 0
missing_counts = pd.Series(dtype="int64")

for chunk in pd.read_csv(path, chunksize=100_000):
    total_rows += len(chunk)
    missing_counts = missing_counts.add(chunk.isna().sum(), fill_value=0)

missing_stats = pd.DataFrame({
    "missing_count": missing_counts.astype("int64"),
    "missing_percent": (missing_counts / total_rows * 100).round(2)
})

missing_stats = missing_stats.sort_values(
    by="missing_percent",
    ascending=False
)

display(missing_stats)

               missing_count  missing_percent
category_code        4034806            98.36
brand                1659261            40.45
user_session             637             0.02
event_time                 0             0.00
category_id                0             0.00
event_type                 0             0.00
price                      0             0.00
product_id                 0             0.00
user_id                    0             0.00

In [20]:
min_date = None
max_date = None

invalid_dates = 0
zero_prices = 0
negative_prices = 0

for chunk in pd.read_csv(
    path,
    usecols=["event_time", "price"],
    chunksize=100_000
):
    dates = pd.to_datetime(
        chunk["event_time"],
        utc=True,
        errors="coerce"
    )

    invalid_dates += dates.isna().sum()
    zero_prices += (chunk["price"] == 0).sum()
    negative_prices += (chunk["price"] < 0).sum()

    chunk_min = dates.min()
    chunk_max = dates.max()

    if pd.notna(chunk_min):
        min_date = chunk_min if min_date is None else min(min_date, chunk_min)

    if pd.notna(chunk_max):
        max_date = chunk_max if max_date is None else max(max_date, chunk_max)

print(f"Начало периода: {min_date}")
print(f"Конец периода: {max_date}")
print(f"Некорректные даты: {invalid_dates}")
print(f"Нулевые цены: {zero_prices}")
print(f"Отрицательные цены: {negative_prices}")

Начало периода: 2019-10-01 00:00:00+00:00
Конец периода: 2019-10-31 23:59:54+00:00
Некорректные даты: 0
Нулевые цены: 6066
Отрицательные цены: 20

In [21]:
purchase_count = 0
zero_purchase = 0
negative_purchase = 0

for chunk in pd.read_csv(
    path,
    usecols=["event_type", "price"],
    chunksize=100_000
):
    purchases = chunk[chunk["event_type"] == "purchase"]

    purchase_count += len(purchases)
    zero_purchase += (purchases["price"] == 0).sum()
    negative_purchase += (purchases["price"] < 0).sum()

print(f"Всего покупок (событий): {purchase_count}")
print(f"Покупок с нулевой ценой: {zero_purchase}")
print(f"Покупок с отрицательной ценой: {negative_purchase}")

Всего покупок (событий): 245624
Покупок с нулевой ценой: 0
Покупок с отрицательной ценой: 20

In [22]:
users = set()
products = set()
sessions = set()

for chunk in pd.read_csv(
    path,
    usecols=["user_id", "product_id", "user_session"],
    chunksize=100_000
):
    users.update(chunk["user_id"].dropna().unique())
    products.update(chunk["product_id"].dropna().unique())
    sessions.update(chunk["user_session"].dropna().unique())

print(f"Уникальных пользователей: {len(users):,}")
print(f"Уникальных товаров: {len(products):,}")
print(f"Уникальных ID сессий: {len(sessions):,}")

Уникальных пользователей: 399,664
Уникальных товаров: 41,899
Уникальных ID сессий: 873,960

In [23]:
session_to_user = {}
conflicting_sessions = set()

for chunk in pd.read_csv(
    path,
    usecols=["user_id", "user_session"],
    chunksize=100_000
):
    pairs = chunk.dropna().drop_duplicates()

    for user, session in pairs.itertuples(index=False, name=None):
        if session in session_to_user:
            if session_to_user[session] != user:
                conflicting_sessions.add(session)
        else:
            session_to_user[session] = user

print(f"Всего ID сессий: {len(session_to_user):,}")
print(f"ID сессий у разных пользователей: {len(conflicting_sessions):,}")
print(f"Доля конфликтных ID: {len(conflicting_sessions) / len(session_to_user) * 100:.4f}%")

Всего ID сессий: 873,960
ID сессий у разных пользователей: 22
Доля конфликтных ID: 0.0025%